name = "Koresh"
license = "Apache-2.0"
description = "Theme for Last Days of Koreshan. Forked from hugo-theme-introduction by Victoria Drake."
tags = [
  "blog",
  "bulma",
  "clean",
  "dark",
  "disqus",
  "font awesome",
  "gallery",
  "minimal",
  "minimalist",
  "mobile",
  "multilingual",
  "one page",
  "personal",
  "responsive",
  "simple",
  "single page",
  "starter",
  "syntax highlighting",
  "projects",
  "white",
]
features = ["responsive", "blog", "portfolio", "gallery"]
min_version = "0.49"

[author]
name     = "Andrey Kaipov"
homepage = "https://kaipov.com"
