baseURL                = "/"
theme                  = "koresh"
DefaultContentLanguage = "en"
buildFuture            = true
googleAnalytics        = "G-PYJLD53W7J"

[permalinks]
blog = "/news/:slug/"

[params]
customCSS = ["css/custom.css"]
customJS  = ["js/custom.js"]

themeStyle    = "light"             # Choose "light" or "dark" or "auto"
favicon       = "/img/fav.png"      # Path to favicon file
showMenu      = true                # Show navigation menu
showRSSButton = false               # Show rss button in navigation
fadeIn        = true                # Turn on/off the fade-in effect
fadeInIndex   = false               # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
dateFormat    = "Jan 2, 2006"
email         = "hello@fried.works" # E-mail address for contact section

    # Configure the home page
    [params.home]
    introHeight           = "fullheight"          # Input either "medium" or "large" or "fullheight"
    heroEmblem            = "/img/angel.png"      # Image shown below the tagline on the home page
    showLatest            = true                  # Show latest blog post summary
    showAllPosts          = true                  # Set true to list all posts on home page, or set false to link to separate blog list page
    allPostsArchiveFormat = true                  # show all posts in an archive format
    localTime             = false                 # Show your current local time in contact section
    timeZone              = "America/Los_Angeles" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    timeFormat            = "en-US"               # Language specific format to use
    # numberOfTeamMembersToShow = 6          # Maximum number of team members to show on home page. Unset or comment out to show all
    [params.team]
    useTwoColumns = false # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
    twitter   = true
    facebook  = true
    pinterest = true

    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    # icon is icon name without the 'fa-'
    [[params.social]]
    url       = "https://www.instagram.com/lastdaysofkoreshan/"
    icon      = "instagram"
    icon_pack = "fab"
    [[params.social]]
    url       = "https://www.youtube.com/@lfried"
    icon      = "youtube"
    icon_pack = "fab"
    [[params.social]]
    url       = "https://www.linkedin.com/in/l-fried-81510a6a"
    icon      = "linkedin-in"
    icon_pack = "fab"
    [[params.social]]
    url       = "https://www.facebook.com/howyoulikeyourcoffee"
    icon      = "facebook-f"
    icon_pack = "fab"
    [[params.social]]
    url       = "mailto:hello@fried.works"
    icon      = "paper-plane"
    icon_pack = "fas"


    # If you don't want to use the default menu, you can define one by yourself
    # [[menu.main]]
    #     name    = "Home"
    #     url     = "/"
    #     weight  = 0
    # [[menu.main]]
    #     name    = "blog"
    #     url     = "/blog/"
    #     weight  = 1


# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
tag    = "tags"
series = "series"


[markup]
defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true
    [markup.highlight]
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ""
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style    = "solarized-dark"
    tabWidth = 4


[languages]
    [languages.en]
    languageName = "English"
    languageCode = "en-us"
    contentDir   = "content"
    weight       = 0
    title        = "Last Days of Koreshan"
        [languages.en.params]
        description = "A historical drama short film based on a true story of a Turn of the Century South Florida cult waiting for the resurrection of their leader."
        footerText  = "[Subscribe to our newsletter →](http://eepurl.com/jpmjF-/) · [⚔](/flaming-sword/ \"The Flaming Sword lights the way\")"
